# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/ehussain/Desktop/Projects/usb/config/cfg/ports.xdc

# XDC: C:/Users/ehussain/Desktop/Projects/usb/config/cfg/clocks.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_clk_in_bufg_0_0/system_clk_in_bufg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_in_bufg_0_0 || ORIG_REF_NAME==system_clk_in_bufg_0_0} -quiet] -quiet

# IP: bd/system/ip/system_variable_clock_div_1_0/system_variable_clock_div_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_variable_clock_div_1_0 || ORIG_REF_NAME==system_variable_clock_div_1_0} -quiet] -quiet

# IP: bd/system/ip/system_gpio_obuf_4_0/system_gpio_obuf_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gpio_obuf_4_0 || ORIG_REF_NAME==system_gpio_obuf_4_0} -quiet] -quiet

# IP: bd/system/ip/system_gpio_obuf_3_0/system_gpio_obuf_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gpio_obuf_3_0 || ORIG_REF_NAME==system_gpio_obuf_3_0} -quiet] -quiet

# IP: bd/system/ip/system_uart_rx_0_0/system_uart_rx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_uart_rx_0_0 || ORIG_REF_NAME==system_uart_rx_0_0} -quiet] -quiet

# IP: bd/system/ip/system_uart_rx_reg_0_0/system_uart_rx_reg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_uart_rx_reg_0_0 || ORIG_REF_NAME==system_uart_rx_reg_0_0} -quiet] -quiet

# IP: bd/system/ip/system_uart_rx_interpreter_0_0/system_uart_rx_interpreter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_uart_rx_interpreter_0_0 || ORIG_REF_NAME==system_uart_rx_interpreter_0_0} -quiet] -quiet

# IP: bd/system/ip/system_outsplitter_0_0/system_outsplitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_outsplitter_0_0 || ORIG_REF_NAME==system_outsplitter_0_0} -quiet] -quiet

# IP: bd/system/ip/system_hex_display_0_0/system_hex_display_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_hex_display_0_0 || ORIG_REF_NAME==system_hex_display_0_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_register_0_0/system_sys_register_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_register_0_0 || ORIG_REF_NAME==system_sys_register_0_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_register_1_0/system_sys_register_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_register_1_0 || ORIG_REF_NAME==system_sys_register_1_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_register_0_1/system_sys_register_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_register_0_1 || ORIG_REF_NAME==system_sys_register_0_1} -quiet] -quiet

# IP: bd/system/ip/system_uart_tx_0_0/system_uart_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_uart_tx_0_0 || ORIG_REF_NAME==system_uart_tx_0_0} -quiet] -quiet

# IP: bd/system/ip/system_uart_tx_viewer_0_0/system_uart_tx_viewer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_uart_tx_viewer_0_0 || ORIG_REF_NAME==system_uart_tx_viewer_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gpio_obuf_3_1/system_gpio_obuf_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gpio_obuf_3_1 || ORIG_REF_NAME==system_gpio_obuf_3_1} -quiet] -quiet

# IP: bd/system/ip/system_gpio_obuf_1_1/system_gpio_obuf_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gpio_obuf_1_1 || ORIG_REF_NAME==system_gpio_obuf_1_1} -quiet] -quiet

# IP: bd/system/ip/system_gpio_obuf_0_1/system_gpio_obuf_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gpio_obuf_0_1 || ORIG_REF_NAME==system_gpio_obuf_0_1} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_register_0_2/system_sys_register_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_register_0_2 || ORIG_REF_NAME==system_sys_register_0_2} -quiet] -quiet

# IP: bd/system/ip/system_variable_clock_div_0_0/system_variable_clock_div_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_variable_clock_div_0_0 || ORIG_REF_NAME==system_variable_clock_div_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gpio_obuf_0_2/system_gpio_obuf_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gpio_obuf_0_2 || ORIG_REF_NAME==system_gpio_obuf_0_2} -quiet] -quiet

# XDC: c:/Users/ehussain/Desktop/Projects/usb/usb.gen/sources_1/bd/system/system_ooc.xdc
